export const crystalInventory = [
  {
    name: "Clear Quartz",
    chineseName: "白水晶",
    color: "Clear",
    energy: ["clarity", "amplification", "balance", "healing"],
  },
  {
    name: "White Azeztulite",
    chineseName: "白阿塞",
    color: "Milky White",
    energy: ["high vibration", "spiritual growth", "purification"],
  },
  {
    name: "Purple Tower Crystal",
    chineseName: "紫塔晶",
    color: "Purple",
    energy: ["intuition", "calmness", "inner wisdom"],
  },
  {
    name: "Uruguayan Amethyst",
    chineseName: "乌拉圭紫",
    color: "Deep Purple",
    energy: ["emotional healing", "protection", "sleep"],
  },
  {
    name: "Aquamarine",
    chineseName: "海蓝宝",
    color: "Light Blue",
    energy: ["peace", "communication", "stress relief"],
  },
  {
    name: "Smoky Quartz",
    chineseName: "茶晶",
    color: "Brown",
    energy: ["grounding", "protection", "stability"],
  },
  {
    name: "Golden Tower Crystal",
    chineseName: "黄塔晶",
    color: "Golden Yellow",
    energy: ["confidence", "abundance", "career"],
  },
  {
    name: "Orange Garnet",
    chineseName: "橙红石榴",
    color: "Orange Red",
    energy: ["passion", "motivation", "vitality"],
  },
  {
    name: "Tiger Eye",
    chineseName: "虎眼石",
    color: "Brown Gold",
    energy: ["confidence", "focus", "protection"],
  },
  {
    name: "Kyanite",
    chineseName: "蓝晶石",
    color: "Blue",
    energy: ["communication", "clarity", "intuition"],
  },
  {
    name: "Prehnite",
    chineseName: "葡萄石",
    color: "Soft Green",
    energy: ["healing", "gentleness", "emotional balance"],
  },
  {
    name: "Obsidian",
    chineseName: "黑曜石",
    color: "Black",
    energy: ["protection", "grounding", "energy shield"],
  },
  {
    name: "Silver Obsidian",
    chineseName: "银曜石",
    color: "Black Silver",
    energy: ["intuition", "protection", "inner reflection"],
  },
  {
    name: "Red Agate",
    chineseName: "红玛瑙",
    color: "Red",
    energy: ["strength", "motivation", "stability"],
  },
  {
    name: "Yellow Flower Crystal",
    chineseName: "黄胶花",
    color: "Yellow",
    energy: ["joy", "positivity", "confidence"],
  },
  {
    name: "Grapefruit Pink Crystal",
    chineseName: "西柚粉",
    color: "Soft Pink",
    energy: ["love", "softness", "self-care"],
  },
  {
    name: "Rose Quartz",
    chineseName: "粉水晶",
    color: "Pink",
    energy: ["love", "self-love", "heart healing"],
  },
];